/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import javax.swing.UIManager;
import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author holas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    private int botonArts,botonMarcas,botonUsuarios;
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public void activarBotones(int a,int b, int c){
        this.botonArts=a;
        this.botonMarcas=b;
        this.botonUsuarios=c;
        if(botonArts==1){
            btnArts.setEnabled(true);
        }
        else{
            btnArts.setEnabled(false);
        }
            if(botonUsuarios==1){
                btnUsuarios.setEnabled(true);
            }
            else{
                btnUsuarios.setEnabled(false);
            }
            if(botonMarcas==1){
                btnMarcas.setEnabled(true);
            }
            else{
                btnMarcas.setEnabled(false);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnArts = new javax.swing.JButton();
        btnMarcas = new javax.swing.JButton();
        btnUsuarios = new javax.swing.JButton();
        dskMDI = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de control de papelería");
        setLocationByPlatform(true);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnArts.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/regla.png"))); // NOI18N
        btnArts.setToolTipText("comando");
        btnArts.setFocusable(false);
        btnArts.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnArts.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnArts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnArts);

        btnMarcas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/pelicano.png"))); // NOI18N
        btnMarcas.setToolTipText("marcas");
        btnMarcas.setFocusable(false);
        btnMarcas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMarcas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnMarcas);

        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/usuario.png"))); // NOI18N
        btnUsuarios.setToolTipText("usuarios");
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnUsuarios);

        javax.swing.GroupLayout dskMDILayout = new javax.swing.GroupLayout(dskMDI);
        dskMDI.setLayout(dskMDILayout);
        dskMDILayout.setHorizontalGroup(
            dskMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dskMDILayout.setVerticalGroup(
            dskMDILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1106, Short.MAX_VALUE)
            .addComponent(dskMDI)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dskMDI))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArtsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtsActionPerformed
        // TODO add your handling code here:
        Articulos a=new Articulos();
        dskMDI.add(a);
        a.setVisible(true);
    }//GEN-LAST:event_btnArtsActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        // TODO add your handling code here:
        Usuarios u=new Usuarios();
        dskMDI.add(u);
        u.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcasActionPerformed
        // TODO add your handling code here:
        Marcas m=new Marcas();
        dskMDI.add(m);
        m.setVisible(true);
    }//GEN-LAST:event_btnMarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
               UIManager.setLookAndFeel("org.jvnet.substance.SubstanceLookAndFeel");
               SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.MangoSkin");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArts;
    private javax.swing.JButton btnMarcas;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JDesktopPane dskMDI;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
