/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import clases.ConectarBase;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author holas
 */
public class Usuarios extends javax.swing.JInternalFrame {

    /**
     * Creates new form Usuarios
     */
    
    ConectarBase conexion=null;
    FileInputStream archivo=null; //obtene el archvo de la magen selecconada
    File fichero=null; //
    InputStream foto=null;
    byte[] bytesImagen=null; //ontene el tamaño en bytes del archvo
    boolean actualiza; //cuando se presiona el boton editar cambia a true
    String idUsuario=null;
    
    public Usuarios() {
        initComponents();
        actualiza=false;
        conexion=new ConectarBase();
        deshabilitarComponentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        herramientas = new javax.swing.JToolBar();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        buscar = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        imprimir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtNombre = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        txtPass2 = new javax.swing.JPasswordField();
        chkArt = new javax.swing.JCheckBox();
        chkMarca = new javax.swing.JCheckBox();
        chkUser = new javax.swing.JCheckBox();
        jSeparator2 = new javax.swing.JSeparator();
        ver = new javax.swing.JButton();
        scroll = new javax.swing.JScrollPane();
        lblFoto = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtArchivo = new javax.swing.JTextField();
        txtUbica = new javax.swing.JTextField();
        Explorar = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setClosable(true);
        setTitle("Usuarios del sistema");

        jLabel1.setText("Nombre o Nickname:");

        jLabel2.setText("Contraseña o password:");

        jLabel3.setText("Confirmar password:");

        jLabel4.setText("Acceso a módulos:");

        herramientas.setFloatable(false);
        herramientas.setRollover(true);

        nuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/nuevo.png"))); // NOI18N
        nuevo.setFocusable(false);
        nuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        nuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        herramientas.add(nuevo);

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/guardar.png"))); // NOI18N
        guardar.setFocusable(false);
        guardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        guardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        herramientas.add(guardar);

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/buscar.png"))); // NOI18N
        buscar.setFocusable(false);
        buscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        herramientas.add(buscar);

        borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrar.png"))); // NOI18N
        borrar.setFocusable(false);
        borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        herramientas.add(borrar);

        editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/editar.png"))); // NOI18N
        editar.setFocusable(false);
        editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        editar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });
        herramientas.add(editar);

        imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/imprimir.png"))); // NOI18N
        imprimir.setFocusable(false);
        imprimir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        imprimir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        herramientas.add(imprimir);

        txtNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtPass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        txtPass2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        chkArt.setText("Artículos");

        chkMarca.setText("Marcas");

        chkUser.setText("Usuarios");

        ver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/ver.png"))); // NOI18N
        ver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                verMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                verMouseReleased(evt);
            }
        });
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        scroll.setViewportView(lblFoto);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Nombre del archivo:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Ubicación");

        Explorar.setText("Explorar");
        Explorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExplorarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(chkArt)
                                .addGap(28, 28, 28)
                                .addComponent(chkMarca)
                                .addGap(45, 45, 45)
                                .addComponent(chkUser))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPass))))
                            .addComponent(jLabel4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(herramientas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPass2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ver))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUbica, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtArchivo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(Explorar))
                                        .addGap(0, 244, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(herramientas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(ver))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(4, 4, 4)
                        .addComponent(txtArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUbica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Explorar)
                        .addGap(0, 41, Short.MAX_VALUE))
                    .addComponent(scroll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkArt)
                    .addComponent(chkMarca)
                    .addComponent(chkUser))
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        // TODO add your handling code here:
        habilitarComponentes();
        limpiarComponentes();
    }//GEN-LAST:event_nuevoActionPerformed
    private void habilitarComponentes(){
     txtNombre.setEnabled(true); txtPass.setEnabled(true);
     txtPass2.setEnabled(true);chkArt.setEnabled(true);
     chkMarca.setEnabled(true); chkUser.setEnabled(true);
     txtNombre.grabFocus(); ver.setEnabled(false);
     Explorar.setEnabled(true);txtUbica.setEnabled(true);
     txtArchivo.setEnabled(true);
    }
    private void limpiarComponentes(){
        txtNombre.setText(""); txtPass.setText("");
        txtPass2.setText("");chkArt.setSelected(false);
        chkMarca.setSelected(false); chkUser.setSelected(false);
        lblFoto.setIcon(null); lblFoto.setText("");
        txtUbica.setText(""); txtArchivo.setText("");
    }
    private void deshabilitarComponentes(){
        txtNombre.setEnabled(false); txtPass.setEnabled(false);
        txtPass2.setEnabled(false);chkArt.setEnabled(false);
        chkMarca.setEnabled(false); chkUser.setEnabled(false);
        ver.setEnabled(false); Explorar.setEnabled(false);
        txtUbica.setEnabled(false); txtArchivo.setEnabled(false);
    }
    
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        PreparedStatement comando=null;
        try{
            int a,b,c;
            if(txtNombre.getText().isEmpty() || txtPass.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Caprura los datos para identificar al usuario");
            }else{
                if(txtPass.getText().matches(txtPass2.getText())){
                    if(actualiza==false){
                        String insertar="INSERT INTO usuarios(nombre,password,articulos,marcas,users,fotografia) VALUES(?,?,?,?,?,?)";
                         comando=(PreparedStatement)conexion.conectar.prepareStatement(insertar);
                    }
                    else{
                        String cambiar="UPDATE usuarios SET nombre=?,password=?,articulos=?,marcas=?,users=?,fotografia=? WHERE id_usuario='"+idUsuario+"'";
                        comando=(PreparedStatement)conexion.conectar.prepareStatement(cambiar);
                        actualiza=false;
                    }
                comando.setString(1, txtNombre.getText());
                comando.setString(2, txtPass.getText());
                a=chkArt.isSelected()?1:0;
                comando.setString(3, String.valueOf(a));
                b=chkMarca.isSelected()?1:0;
                comando.setString(4, String.valueOf(b));
                c=chkUser.isSelected()?1:0;
                comando.setString(5, String.valueOf(c));
                if(foto==null) foto=new FileInputStream(new File(fichero.getAbsolutePath()));
                comando.setBinaryStream(6,foto);
                comando.executeUpdate();
               JOptionPane.showMessageDialog(null, "Usuario registrado exitosamente");
               limpiarComponentes();
               deshabilitarComponentes();
                }else{
                JOptionPane.showMessageDialog(null,"Los password's no coinciden");
                txtPass.setText("");
                txtPass2.setText("");
                txtPass.grabFocus();
                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error al Registrar al usuario  verifique.....");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(rootPane,"Error al obtener el archivo de la imagen");
        }
    }//GEN-LAST:event_guardarActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        // TODO add your handling code here:
        try{
            limpiarComponentes();
            deshabilitarComponentes();
            String nom=JOptionPane.showInputDialog("Usuario a buscar");
            String consulta="SELECT * FROM usuarios WHERE nombre=?";
            PreparedStatement comando=(PreparedStatement)conexion.conectar.prepareStatement(consulta);
            comando.setString(1,nom);
            ResultSet registro=comando.executeQuery();
            if(registro.next()){
                idUsuario=registro.getString(1);
                txtNombre.setText(registro.getString(2));
                txtPass.setText(registro.getString(3));
                txtPass2.setText(registro.getString(3));
                if(registro.getInt(4)==1)chkArt.setSelected(true);
                if(registro.getInt(5)==1)chkMarca.setSelected(true);
                if(registro.getInt(6)==1)chkUser.setSelected(true);
                if(registro.getBytes(7)!=null){
                    bytesImagen=registro.getBytes(7);
                    foto=registro.getBinaryStream(7);
                    lblFoto.setIcon(new ImageIcon(bytesImagen));
                }
                else{
                    lblFoto.setIcon(null);
                    lblFoto.setText("Sin imagen");
                    foto=null;
                }
            }    
                else{
                    JOptionPane.showMessageDialog(rootPane,"Usuario inexistente...");
                }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Error al efectuar la consulta");
        }
                
    }//GEN-LAST:event_buscarActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        // TODO add your handling code here:
        /*try{
            if(txtCodigo.getText().isEmpty()){
                JOptionPane.showMessageDialog(rootPane,"Primero busque al atículo");
            }
            else{
                int resp=JOptionPane.showConfirmDialog(rootPane,"¿Estás segur@ que quieres borrar el artículo?","Borrar artículo",JOptionPane.YES_NO_OPTION);
                if(resp==0){
                    String borrar="DELETE FROM articulos WHERE codigo=?";
                    PreparedStatement comando=(PreparedStatement)conexion.conectar.prepareStatement(borrar);
                    comando.setString(1,txtCodigo.getText());
                    comando.executeUpdate();
                    JOptionPane.showMessageDialog(rootPane,"Artículo borrado con éxito");
                    limpiarComponentes();
                }
            }

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Error al tratar de borrar al artículo");
        }*/
    }//GEN-LAST:event_borrarActionPerformed

    private void verMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMousePressed
        // TODO add your handling code here:
        if(evt.getButton()==1)txtPass.setEchoChar((char)0);//0
        if(evt.getButton()==1)txtPass2.setEchoChar((char)0);
    }//GEN-LAST:event_verMousePressed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verActionPerformed

    private void verMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_verMouseReleased
        // TODO add your handling code here:
        if(evt.getButton()==1)txtPass.setEchoChar('*');
        if(evt.getButton()==1)txtPass2.setEchoChar('*');
    }//GEN-LAST:event_verMouseReleased

    private void ExplorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExplorarActionPerformed
        // TODO add your handling code here:
        JFileChooser archivoImagen=new JFileChooser();
        FileNameExtensionFilter filtro=new FileNameExtensionFilter("Imágenes","jpg","png","gif","bmp");
        archivoImagen.setFileFilter(filtro);
        archivoImagen.showOpenDialog(this);
        fichero=archivoImagen.getSelectedFile();
        if(fichero!=null){
            txtArchivo.setText(fichero.getName());
            txtUbica.setText(fichero.getAbsolutePath());
            bytesImagen=new byte[512000];
            try{
                archivo=new FileInputStream(fichero);
                archivo.read(bytesImagen);
                if(archivo.read()<=512000){
                    lblFoto.setIcon(new ImageIcon(bytesImagen));
                    lblFoto.setText("");
                    foto=null;
                }
                else{
                    JOptionPane.showMessageDialog(rootPane,"La imagen no debe exceder 512Kb");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(archivoImagen,"Error al obtener");
            }
        }
    }//GEN-LAST:event_ExplorarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        // TODO add your handling code here:
        if(txtNombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Primero busque al usuario a editar");
        }
        else{
            actualiza=true;
            habilitarComponentes();
            
        }
    }//GEN-LAST:event_editarActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Explorar;
    private javax.swing.JButton borrar;
    private javax.swing.JButton buscar;
    private javax.swing.JCheckBox chkArt;
    private javax.swing.JCheckBox chkMarca;
    private javax.swing.JCheckBox chkUser;
    private javax.swing.JButton editar;
    private javax.swing.JButton guardar;
    private javax.swing.JToolBar herramientas;
    private javax.swing.JButton imprimir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JButton nuevo;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTextField txtArchivo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtUbica;
    private javax.swing.JButton ver;
    // End of variables declaration//GEN-END:variables
}
